/* Generated by re2c */
#include "lexer.hxx"

#include "utils/diag.hxx"
#include "options.hxx"

#include <cassert>
#include <cstdio>
#include <cstring>



void
PLexer::tokenize(PToken& p_token)
{
#define FILL_TOKEN(p_kind) (fill_token(p_token, p_kind))

    for (;;) {
        m_marked_cursor = m_cursor;
        m_marked_source_location = m_marked_cursor - source_file->get_buffer_raw();


        
{
    char yych;
    unsigned int yyaccept = 0;
    yych = *m_cursor;
    switch (yych) {
        case 0x00: goto yy1;
        case '\t':
        case '\v':
        case '\f':
        case ' ': goto yy4;
        case '\n': goto yy7;
        case '\r': goto yy8;
        case '!': goto yy9;
        case '"': goto yy11;
        case '%': goto yy12;
        case '&': goto yy14;
        case '(': goto yy16;
        case ')': goto yy17;
        case '*': goto yy18;
        case '+': goto yy20;
        case ',': goto yy22;
        case '-': goto yy23;
        case '.': goto yy25;
        case '/': goto yy26;
        case '0': goto yy28;
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9': goto yy30;
        case ':': goto yy32;
        case ';': goto yy33;
        case '<': goto yy34;
        case '=': goto yy36;
        case '>': goto yy38;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z': goto yy40;
        case '[': goto yy43;
        case ']': goto yy44;
        case '^': goto yy45;
        case 'r': goto yy47;
        case '{': goto yy48;
        case '|': goto yy49;
        case '}': goto yy51;
        default: goto yy2;
    }
yy1:
    ++m_cursor;
    {
                fill_token(p_token, P_TOK_EOF);
                p_token.token_length = 0;
                m_cursor--;
                break;
            }
yy2:
    ++m_cursor;
yy3:
    {
                PDiag* d = diag_at(P_DK_err_unknown_character, m_marked_source_location);
                diag_add_arg_char(d, m_cursor[-1]);
                diag_flush(d);
                continue;
            }
yy4:
    yych = *++m_cursor;
yy5:
    switch (yych) {
        case '\t':
        case '\v':
        case '\f':
        case '\r':
        case ' ': goto yy4;
        default: goto yy6;
    }
yy6:
    { continue; }
yy7:
    ++m_cursor;
    {
                register_newline();
                continue;
            }
yy8:
    yych = *++m_cursor;
    switch (yych) {
        case '\n': goto yy7;
        default: goto yy5;
    }
yy9:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy52;
        default: goto yy10;
    }
yy10:
    { return fill_token(p_token, P_TOK_EXCLAIM); }
yy11:
    yyaccept = 0;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case 0x00:
        case '\n':
        case '\r': goto yy3;
        default: goto yy54;
    }
yy12:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy58;
        default: goto yy13;
    }
yy13:
    { return fill_token(p_token, P_TOK_PERCENT); }
yy14:
    yych = *++m_cursor;
    switch (yych) {
        case '&': goto yy59;
        case '=': goto yy60;
        default: goto yy15;
    }
yy15:
    { return fill_token(p_token, P_TOK_AMP); }
yy16:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_LPAREN); }
yy17:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_RPAREN); }
yy18:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy61;
        default: goto yy19;
    }
yy19:
    { return fill_token(p_token, P_TOK_STAR); }
yy20:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy62;
        default: goto yy21;
    }
yy21:
    { return fill_token(p_token, P_TOK_PLUS); }
yy22:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_COMMA); }
yy23:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy63;
        case '>': goto yy64;
        default: goto yy24;
    }
yy24:
    { return fill_token(p_token, P_TOK_MINUS); }
yy25:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_DOT); }
yy26:
    yych = *++m_cursor;
    switch (yych) {
        case '*': goto yy65;
        case '/': goto yy66;
        case '=': goto yy68;
        default: goto yy27;
    }
yy27:
    { return fill_token(p_token, P_TOK_SLASH); }
yy28:
    yyaccept = 1;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case 'B':
        case 'b': goto yy70;
        case 'O':
        case 'o': goto yy72;
        case 'X':
        case 'x': goto yy73;
        default: goto yy31;
    }
yy29:
    { return fill_integer_literal(p_token, 10); }
yy30:
    yyaccept = 1;
    yych = *(m_marker = ++m_cursor);
yy31:
    switch (yych) {
        case '.': goto yy69;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '_': goto yy30;
        case 'E':
        case 'e': goto yy71;
        case 'f': goto yy74;
        case 'i':
        case 'u': goto yy75;
        default: goto yy29;
    }
yy32:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_COLON); }
yy33:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_SEMI); }
yy34:
    yych = *++m_cursor;
    switch (yych) {
        case '<': goto yy76;
        case '=': goto yy78;
        default: goto yy35;
    }
yy35:
    { return fill_token(p_token, P_TOK_LESS); }
yy36:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy79;
        default: goto yy37;
    }
yy37:
    { return fill_token(p_token, P_TOK_EQUAL); }
yy38:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy80;
        case '>': goto yy81;
        default: goto yy39;
    }
yy39:
    { return fill_token(p_token, P_TOK_GREATER); }
yy40:
    yych = *++m_cursor;
yy41:
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z': goto yy40;
        default: goto yy42;
    }
yy42:
    { return fill_identifier_token(p_token, false); }
yy43:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_LSQUARE); }
yy44:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_RSQUARE); }
yy45:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy83;
        default: goto yy46;
    }
yy46:
    { return fill_token(p_token, P_TOK_CARET); }
yy47:
    yyaccept = 2;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '#': goto yy84;
        default: goto yy41;
    }
yy48:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_LBRACE); }
yy49:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy85;
        case '|': goto yy86;
        default: goto yy50;
    }
yy50:
    { return fill_token(p_token, P_TOK_PIPE); }
yy51:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_RBRACE); }
yy52:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_EXCLAIM_EQUAL); }
yy53:
    yych = *++m_cursor;
yy54:
    switch (yych) {
        case 0x00:
        case '\n':
        case '\r': goto yy55;
        case '"': goto yy56;
        case '\\': goto yy57;
        default: goto yy53;
    }
yy55:
    m_cursor = m_marker;
    switch (yyaccept) {
        case 0: goto yy3;
        case 1: goto yy29;
        case 2: goto yy42;
        case 3: goto yy90;
        case 4: goto yy92;
        case 5: goto yy97;
        default: goto yy99;
    }
yy56:
    ++m_cursor;
    { return fill_string_literal(p_token); }
yy57:
    yych = *++m_cursor;
    switch (yych) {
        case '"':
        case '\'':
        case '0':
        case '\\':
        case 'n':
        case 'r':
        case 't': goto yy53;
        case 'u': goto yy87;
        case 'x': goto yy88;
        default: goto yy55;
    }
yy58:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_PERCENT_EQUAL); }
yy59:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_AMP_AMP); }
yy60:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_AMP_EQUAL); }
yy61:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_STAR_EQUAL); }
yy62:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_PLUS_EQUAL); }
yy63:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_MINUS_EQUAL); }
yy64:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_ARROW); }
yy65:
    ++m_cursor;
    { goto block_comment; }
yy66:
    yych = *++m_cursor;
    switch (yych) {
        case 0x00:
        case '\n':
        case '\r': goto yy67;
        default: goto yy66;
    }
yy67:
    {
                if (!m_keep_comments)
                    continue;

                fill_token(p_token, P_TOK_COMMENT);
                p_token.data.literal.begin = m_marked_cursor;
                p_token.data.literal.end = m_cursor;
                break;
            }
yy68:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_SLASH_EQUAL); }
yy69:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9': goto yy89;
        default: goto yy55;
    }
yy70:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1': goto yy91;
        case '_': goto yy70;
        default: goto yy55;
    }
yy71:
    yych = *++m_cursor;
    switch (yych) {
        case '+':
        case '-': goto yy93;
        default: goto yy94;
    }
yy72:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7': goto yy96;
        case '_': goto yy72;
        default: goto yy55;
    }
yy73:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy98;
        case '_': goto yy73;
        default: goto yy55;
    }
yy74:
    yych = *++m_cursor;
    switch (yych) {
        case '3': goto yy100;
        case '6': goto yy101;
        default: goto yy55;
    }
yy75:
    yych = *++m_cursor;
    switch (yych) {
        case '1': goto yy102;
        case '3': goto yy103;
        case '6': goto yy104;
        case '8': goto yy105;
        default: goto yy55;
    }
yy76:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy106;
        default: goto yy77;
    }
yy77:
    { return fill_token(p_token, P_TOK_LESS_LESS); }
yy78:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_LESS_EQUAL); }
yy79:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_EQUAL_EQUAL); }
yy80:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_GREATER_EQUAL); }
yy81:
    yych = *++m_cursor;
    switch (yych) {
        case '=': goto yy107;
        default: goto yy82;
    }
yy82:
    { return fill_token(p_token, P_TOK_GREATER_GREATER); }
yy83:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_CARET_EQUAL); }
yy84:
    yych = *++m_cursor;
    switch (yych) {
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z': goto yy108;
        default: goto yy55;
    }
yy85:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_PIPE_EQUAL); }
yy86:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_PIPE_PIPE); }
yy87:
    yych = *++m_cursor;
    switch (yych) {
        case '{': goto yy110;
        default: goto yy55;
    }
yy88:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7': goto yy111;
        default: goto yy55;
    }
yy89:
    yyaccept = 3;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '_': goto yy89;
        case 'E':
        case 'e': goto yy71;
        case 'f': goto yy74;
        default: goto yy90;
    }
yy90:
    {
                FILL_TOKEN(P_TOK_FLOAT_LITERAL);
                p_token.data.literal.begin = m_marked_cursor;
                p_token.data.literal.end = m_cursor;

                PFloatLiteralSuffix suffix = P_FLS_NO_SUFFIX;
                if (p_token.data.literal.end - p_token.data.literal.begin >= 3) {
                    const char* suffix_start = p_token.data.literal.end - 3;
                    if (memcmp(suffix_start, "f32", 3) == 0) {
                        suffix = P_FLS_F32;
                        p_token.data.literal.end -= 3;
                    } else if (memcmp(suffix_start, "f64", 3) == 0) {
                        suffix = P_FLS_F64;
                        p_token.data.literal.end -= 3;
                    }
                }

                p_token.data.literal.suffix_kind = suffix;

                break;
            }
yy91:
    yyaccept = 4;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '0':
        case '1':
        case '_': goto yy91;
        case 'i':
        case 'u': goto yy112;
        default: goto yy92;
    }
yy92:
    { return fill_integer_literal(p_token, 2); }
yy93:
    yych = *++m_cursor;
yy94:
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9': goto yy95;
        case '_': goto yy93;
        default: goto yy55;
    }
yy95:
    yyaccept = 3;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '_': goto yy95;
        case 'f': goto yy74;
        default: goto yy90;
    }
yy96:
    yyaccept = 5;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '_': goto yy96;
        case 'i':
        case 'u': goto yy113;
        default: goto yy97;
    }
yy97:
    { return fill_integer_literal(p_token, 8); }
yy98:
    yyaccept = 6;
    yych = *(m_marker = ++m_cursor);
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy98;
        case 'i':
        case 'u': goto yy114;
        default: goto yy99;
    }
yy99:
    { return fill_integer_literal(p_token, 16); }
yy100:
    yych = *++m_cursor;
    switch (yych) {
        case '2': goto yy115;
        default: goto yy55;
    }
yy101:
    yych = *++m_cursor;
    switch (yych) {
        case '4': goto yy115;
        default: goto yy55;
    }
yy102:
    yych = *++m_cursor;
    switch (yych) {
        case '6': goto yy105;
        default: goto yy55;
    }
yy103:
    yych = *++m_cursor;
    switch (yych) {
        case '2': goto yy105;
        default: goto yy55;
    }
yy104:
    yych = *++m_cursor;
    switch (yych) {
        case '4': goto yy105;
        default: goto yy55;
    }
yy105:
    ++m_cursor;
    goto yy29;
yy106:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_LESS_LESS_EQUAL); }
yy107:
    ++m_cursor;
    { return fill_token(p_token, P_TOK_GREATER_GREATER_EQUAL); }
yy108:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z': goto yy108;
        default: goto yy109;
    }
yy109:
    { return fill_identifier_token(p_token, true); }
yy110:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy116;
        default: goto yy55;
    }
yy111:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy53;
        default: goto yy55;
    }
yy112:
    yych = *++m_cursor;
    switch (yych) {
        case '1': goto yy117;
        case '3': goto yy118;
        case '6': goto yy119;
        case '8': goto yy120;
        default: goto yy55;
    }
yy113:
    yych = *++m_cursor;
    switch (yych) {
        case '1': goto yy121;
        case '3': goto yy122;
        case '6': goto yy123;
        case '8': goto yy124;
        default: goto yy55;
    }
yy114:
    yych = *++m_cursor;
    switch (yych) {
        case '1': goto yy125;
        case '3': goto yy126;
        case '6': goto yy127;
        case '8': goto yy128;
        default: goto yy55;
    }
yy115:
    ++m_cursor;
    goto yy90;
yy116:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy129;
        case '_': goto yy116;
        case '}': goto yy53;
        default: goto yy55;
    }
yy117:
    yych = *++m_cursor;
    switch (yych) {
        case '6': goto yy120;
        default: goto yy55;
    }
yy118:
    yych = *++m_cursor;
    switch (yych) {
        case '2': goto yy120;
        default: goto yy55;
    }
yy119:
    yych = *++m_cursor;
    switch (yych) {
        case '4': goto yy120;
        default: goto yy55;
    }
yy120:
    ++m_cursor;
    goto yy92;
yy121:
    yych = *++m_cursor;
    switch (yych) {
        case '6': goto yy124;
        default: goto yy55;
    }
yy122:
    yych = *++m_cursor;
    switch (yych) {
        case '2': goto yy124;
        default: goto yy55;
    }
yy123:
    yych = *++m_cursor;
    switch (yych) {
        case '4': goto yy124;
        default: goto yy55;
    }
yy124:
    ++m_cursor;
    goto yy97;
yy125:
    yych = *++m_cursor;
    switch (yych) {
        case '6': goto yy128;
        default: goto yy55;
    }
yy126:
    yych = *++m_cursor;
    switch (yych) {
        case '2': goto yy128;
        default: goto yy55;
    }
yy127:
    yych = *++m_cursor;
    switch (yych) {
        case '4': goto yy128;
        default: goto yy55;
    }
yy128:
    ++m_cursor;
    goto yy99;
yy129:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy130;
        case '_': goto yy129;
        case '}': goto yy53;
        default: goto yy55;
    }
yy130:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy131;
        case '_': goto yy130;
        case '}': goto yy53;
        default: goto yy55;
    }
yy131:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy132;
        case '_': goto yy131;
        case '}': goto yy53;
        default: goto yy55;
    }
yy132:
    yych = *++m_cursor;
    switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f': goto yy133;
        case '_': goto yy132;
        case '}': goto yy53;
        default: goto yy55;
    }
yy133:
    yych = *++m_cursor;
    switch (yych) {
        case '_': goto yy133;
        case '}': goto yy53;
        default: goto yy55;
    }
}


        block_comment:
        
{
    char yych;
    yych = *m_cursor;
    switch (yych) {
        case 0x00: goto yy135;
        case '\n': goto yy138;
        case '\r': goto yy139;
        case '*': goto yy140;
        default: goto yy136;
    }
yy135:
    ++m_cursor;
    {
                // Unterminated block comment
                fill_token(p_token, P_TOK_EOF);
                m_cursor--;
                break;
            }
yy136:
    ++m_cursor;
yy137:
    {
                goto block_comment;
            }
yy138:
    ++m_cursor;
    {
                register_newline();
                goto block_comment;
            }
yy139:
    yych = *++m_cursor;
    switch (yych) {
        case '\n': goto yy138;
        default: goto yy137;
    }
yy140:
    yych = *++m_cursor;
    switch (yych) {
        case '/': goto yy141;
        default: goto yy137;
    }
yy141:
    ++m_cursor;
    {
                if (!m_keep_comments)
                    continue;

                fill_token(p_token, P_TOK_COMMENT);
                p_token.data.literal.begin = m_marked_cursor;
                p_token.data.literal.end = m_cursor;
                break;
            }
}

    }

#undef FILL_TOKEN
}
